name: Regional Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:

  americas:
    runs-on: ubuntu-latest

    concurrency:
      group: regional-push
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npx playwright install chromium

      - run: node regional-americas.js

      - name: Commit JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || git commit -m "update americas"

          git pull --rebase origin main
          git push

  europe:
    runs-on: ubuntu-latest

    concurrency:
      group: regional-push
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npx playwright install chromium

      - run: node regional-europe.js

      - name: Commit JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || git commit -m "update europe"

          git pull --rebase origin main
          git push

  asia:
    runs-on: ubuntu-latest

    concurrency:
      group: regional-push
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npx playwright install chromium

      - run: node regional-asia.js

      - name: Commit JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || git commit -m "update asia"

          git pull --rebase origin main
          git push

  mea:
    runs-on: ubuntu-latest

    concurrency:
      group: regional-push
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npx playwright install chromium

      - run: node regional-mea.js

      - name: Commit JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || git commit -m "update mea"

          git pull --rebase origin main
          git push
