name: Regional Charts

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

concurrency:
  group: regional-charts
  cancel-in-progress: true

jobs:
  americas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Americas
        run: node regional-americas.js

      - name: Commit Americas
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "update americas"

            until git push; do
              echo "Retry push 😭"
              git pull --rebase origin main
              sleep 3
            done
          fi

  europe:
    needs: americas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Europe
        run: node regional-europe.js

      - name: Commit Europe
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "update europe"

            until git push; do
              echo "Retry push 😭"
              git pull --rebase origin main
              sleep 3
            done
          fi

  asia:
    needs: europe
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Asia
        run: node regional-asia.js

      - name: Commit Asia
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "update asia"

            until git push; do
              echo "Retry push 😭"
              git pull --rebase origin main
              sleep 3
            done
          fi

  mea:
    needs: asia
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run MEA
        run: node regional-mea.js

      - name: Commit MEA
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "update mea"

            until git push; do
              echo "Retry push 😭"
              git pull --rebase origin main
              sleep 3
            done
          fi

  merge:
    needs: mea
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Merge
        run: node merge-regional.js

      - name: Commit Regional
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add regional.json

          if ! git diff --cached --quiet; then
            git commit -m "update regional"

            until git push; do
              echo "Retry push 😭"
              git pull --rebase origin main
              sleep 3
            done
          fi
